language: minimal

install: true

before_script: pip install --user awscli

script: aws s3 sync . s3://serverless-days-zurich --delete --exclude .git/ --exclude .travis.yml --exclude README.md --acl public-read --cache-control max-age=1800

notifications:
  email:
    - d.madama@gmail.com
    - stefano.cicatiello@xpeppers.com